services:
  - type: web
    name: govno-afaoni-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DB_PATH
        value: /tmp/game.db
